apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-deploy
  name: my-deploy
spec:
  strategy:
   type: RollingUpdate
   rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 10
  selector:
    matchLabels:
      app: my-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-deploy
    spec:
      containers:
        - image: httpd:latest
          name: httpd


